variables:
  REPOSITORY: "registry.jiagouyun.com/cloudcare-front/dataflux-func-site"

  OSS_RESOURCE_BASE_URL: oss://zhuyun-static-files-production/dataflux-func/resource
  OSS_ENDPOINT         : http://oss-cn-hangzhou-internal.aliyuncs.com
stages:
  - build

job_build:
  stage: build
  only:
    - master
  script:
    - docker build -t $REPOSITORY:$CI_COMMIT_REF_SLUG .
    - docker push $REPOSITORY:$CI_COMMIT_REF_SLUG
    - tools/ossutil64 cp contents ${OSS_RESOURCE_BASE_URL}/docs -r -f -e ${OSS_ENDPOINT} -i ${ZY_STATIC_OSS_AK_ID} -k ${ZY_STATIC_OSS_AK_SECRET}
  tags:
    - cloudcare
